/*
 * TIMER_Config.h
 *
 *  Created on: Nov 18, 2023
 *      Author: Yasmin
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/*Timer0 Prescaler Options:
 * 1- NO_CLOCK_SOURCE_TIMER0_STOPPED
 * 2- TIMER0_NO_PRESCALER
 * 3- TIMER0_8_PRESCALER
 * 4- TIMER0_64_PRESCALER
 * 5- TIMER0_256_PRESCALER
 * 6- TIMER0_1024_PRESCALER
 * 7- TIMER0_EXTERNAL_CLOCK_FALLING_EDGE
 * 8- TIMER0_EXTERNAL_CLOCK_RAISING_EDGE
 */
#define TIMER0_SET_PRESCALER   TIMER0_8_PRESCALER

/*Timer0 Mode Options:
 * 1- TIMER0_NORMAL_MODE
 * 2- TIMER0_CTC_MODE
 * 3- TIMER0_FAST_PWM_MODE
 * 4- TIMER0_PHASE_CORRECT_PWM_MODE
 */
#define TIMER0_SET_MODE   TIMER0_NORMAL_MODE

/*Timer0 CTC OC0 Pin Options:
 * 1- TIMER0_OC0_DISCONNECTED
 * 2- TIMER0_OC0_TOGGLE
 * 3- TIMER0_OC0_CLEAR
 * 4- TIMER0_OC0_SET
 */
#define TIMER0_OC0_MODE   TIMER0_OC0_TOGGLE

/*Timer0 Fast PWM OC0 Pin Options:
 * 1- TIMER0_OC0_NON_INVERTING
 * 2- TIMER0_OC0_INVERTING
 */
#define TIMER0_FAST_PWM_OC0_MODE    TIMER0_OC0_NON_INVERTING

/*Timer0 Phase Correct PWM OC0 Pin Options:
 * 1- TIMER0_OC0_NON_INVERTING
 * 2- TIMER0_OC0_INVERTING
 */
#define TIMER0_PHASE_CORRECT_PWM_OC0_MODE    TIMER0_OC0_NON_INVERTING

/*Timer1 Channel Options:
 * 1- TIMER1_CHANNEL_A
 * 2- TIMER1_CHANNEL_B
 */
#define TIMER1_CHANNEL   TIMER1_CHANNEL_A

/*Timer1 Prescaler Options:
 * 1- NO_CLOCK_SOURCE_TIMER1_STOPPED
 * 2- TIMER1_NO_PRESCALER
 * 3- TIMER1_8_PRESCALER
 * 4- TIMER1_64_PRESCALER
 * 5- TIMER1_256_PRESCALER
 * 6- TIMER1_1024_PRESCALER
 * 7- TIMER1_EXTERNAL_CLOCK_FALLING_EDGE
 * 8- TIMER1_EXTERNAL_CLOCK_RAISING_EDGE
 */
#define TIMER1_SET_PRESCALER   TIMER1_NO_PRESCALER

/*Timer1 Mode Options:
 * 1- TIMER1_NORMAL_MODE
 * 2- TIMER1_PHASE_CORRECT_PWM_8_BIT_MODE
 * 3- TIMER1_PHASE_CORRECT_PWM_9_BIT_MODE
 * 4- TIMER1_PHASE_CORRECT_PWM_10_BIT_MODE
 * 5- TIMER1_CTC_MODE
 * 6- TIMER1_FAST_PWM_8_BIT_MODE
 * 7- TIMER1_FAST_PWM_9_BIT_MODE
 * 8- TIMER1_FAST_PWM_10_BIT_MODE
 * 9- TIMER1_PHASE_AND_FREQUENCY_CORRECT_ICR1_AS_TOP_MODE
 * 10- TIMER1_PHASE_AND_FREQUENCY_CORRECT_OCR1A_AS_TOP_MODE
 * 11- TIMER1_PHASE_CORRECT_ICR1_AS_TOP_MODE
 * 12- TIMER1_PHASE_CORRECT_OCR1A_AS_TOP_MODE
 * 13- TIMER1_CTC_ICR1_AS_TOP_MODE
 * 14- TIMER1_FAST_PWM_ICR1_AS_TOP_MODE
 * 15- TIMER1_FAST_PWM_OCR1A_AS_TOP_MODE
 */
#define TIMER1_SET_MODE   TIMER1_NORMAL_MODE

/*Timer1 CTC OC1A/OC1B Pin Options:
 * 1- TIMER1_CTC_OC1A_AND_OC1B_DISCONNECRED
 * 2- TIMER1_CTC_OC1A_AND_OC1B_TOGGLE
 * 3- TIMER1_CTC_OC1A_AND_OC1B_CLEAR
 * 4- TIMER1_CTC_OC1A_AND_OC1B_SET
 */
#define TIMER1_CTC_OC1A_AND_OC1B_MODE   TIMER1_CTC_OC1A_AND_OC1B_DISCONNECRED

/*Timer1 Fast PWM OC1A/OC1B Pin Options:
 * 1- TIMER1_FAST_PWM_OC1A_AND_OC1B_DISCONNECTED
 * 2- TIMER1_FAST_PWM_OC1A_TOGGLE_OC1B_DISCONNECTED
 * 3- TIMER1_FAST_PWM_OC1A_AND_OC1B_NON_INVERTING
 * 4- TIMER1_FAST_PWM_OC1A_AND_OC1B_INVERTING
 */
#define TIMER1_FAST_PWM_OC1A_AND_OC1B_MODE   TIMER1_FAST_PWM_OC1A_AND_OC1B_DISCONNECTED

/*Timer1 Phase Correct PWM OC1A/OC1B Pin Options:
 * 1- TIMER1_PHASE_CORRECT_PWM_OC1A_AND_OC1B_DISCONNECTED
 * 2- TIMER1_PHASE_CORRECT_PWM_OC1A_TOGGLE_OC1B_DISCONNECTED
 * 3- TIMER1_PHASE_CORRECT_PWM_OC1A_AND_OC1B_NON_INVERTING
 * 4- TIMER1_PHASE_CORRECT_PWM_OC1A_AND_OC1B_INVERTING
 */
#define TIMER1_PHASE_CORRECT_PWM_OC1A_AND_OC1B_MODE   TIMER1_PHASE_CORRECT_PWM_OC1A_AND_OC1B_DISCONNECTED

/*Timer1 ICU Sense Edge Options:
 * 1- TIMER1_ICU_RAISING_EDGE
 * 2- TIMER1_ICU_FALLING_EDGE
 */

/*Timer2 Prescaler Options:
 * 1- NO_CLOCK_SOURCE_TIMER2_STOPPED
 * 2- TIMER2_NO_PRESCALER
 * 3- TIMER2_8_PRESCALER
 * 4- TIMER2_32_PRESCALER
 * 5- TIMER2_64_PRESCALER
 * 6- TIMER2_128_PRESCALER
 * 7- TIMER2_256_PRESCALER
 * 8- TIMER2_1024_PRESCALER
 */
#define TIMER2_SET_PRESCALER   TIMER2_256_PRESCALER

/*Timer2 Mode Options:
 * 1- TIMER2_NORMAL_MODE
 * 2- TIMER2_CTC_MODE
 * 3- TIMER2_FAST_PWM_MODE
 * 4- TIMER2_PHASE_CORRECT_PWM_MODE
 */
#define TIMER2_SET_MODE   TIMER2_FAST_PWM_MODE

/*Timer2 Fast PWM OC2 Pin Options:
 * 1- TIMER2_OC2_NON_INVERTING
 * 2- TIMER2_OC2_INVERTING
 */
#define TIMER2_FAST_PWM_OC2_MODE    TIMER2_OC2_NON_INVERTING

/*Timer2 Phase Correct PWM OC2 Pin Options:
 * 1- TIMER2_OC2_NON_INVERTING
 * 2- TIMER2_OC2_INVERTING
 */
#define TIMER2_PHASE_CORRECT_PWM_OC2_MODE    TIMER2_OC2_NON_INVERTING

#endif /* TIMER_CONFIG_H_ */
